name: xeus-python-kernel
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - traitlets
  - requests
  - typer
  - pytest
  - emsdk >=3.1.11
  - pip:
    - empack >=2.0.6,<3
    - jupyterlite
