name: xeus-python-kernel
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - traitlets
  - requests
  - typer
  - pytest
  - emsdk >=3.1.11
  - empack >=2.0.8,<3
  - pip:
    - jupyterlite
