name: xeus-python-kernel
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - traitlets
  - requests
  - typer
  - pytest
  - emsdk >=3.1.11
  - pip:
    - git+https://github.com/martinRenou/empack.git@synchronous_imports_packages
    - jupyterlite
