name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - python=3.10
  - click
  - typer
  - mamba
  - pydata-sphinx-theme
  - pip
  - pip:
    - jupyterlite==0.1.0b16
    - jupyterlite-sphinx
    - empack>=2.0.3
    - ..
