name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - click
  - typer
  - pydata-sphinx-theme
  - yarn
  - jupyterlab
  - pip:
    - git+https://github.com/martinRenou/empack.git@synchronous_imports_packages
    - jupyterlite==0.1.0b17
    - jupyterlite-sphinx
    - ..
