name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - yarn
  - jupyterlab
  - jupyter-packaging
  - pydata-sphinx-theme
  - emsdk

  - pip:
    - jupyterlite-xeus-python==0.2.0
    - jupyterlite-sphinx
