name: xeus-python-kernel-docs

channels:
  - conda-forge

dependencies:
  - mamba
  - pydata-sphinx-theme
  - pip
  - pip:
      - jupyterlite==0.1.0b16
      - jupyterlite-sphinx
      - jupyterlite-xeus-python>=0.5.0
